permalink: pretty
title: mrrobust - Two-sample Mendelian randomization in Stata
email: tom.palmer@lancaster.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  Stata package for two-sample Mendelian randomization analyses
baseurl: "/mrrobust" # the subpath of your site, e.g. /blog
url: "https://remlapmot.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username: remlapmot
keywords: "Mendelian randomization, Stata, Two-sample"
author: Tom Palmer
repo: "https://github.com/remlapmot/mrrobust"
exclude: cscripts/README.md
header_pages: 
 - index.md
 - mrrobust-examples.md
 - spiller-ije-2018-examples.md
 - markstat-call-R-example.md
 - rmarkdown-call-stata-example.md
 - save-estimates.md

# Build settings
markdown: kramdown
# theme: jekyll-theme-slate 
theme: minima
plugins:
  - jekyll-feed

# defaults (to simplify front matter)
defaults:
  - scope:
      path: ""
    values:
      layout: default
